[[redirects]]
  from = "/"
  to = "https://recaptime.eu.org"

[[redirects]]
  from = "/about"
  to = "https://recaptime.eu.org/about"

[[redirects]]
  from = "/community"
  to = "https://recaptime.eu.org/community"

[[redirects]]
  from = "/*"
  to = "https://recaptime.eu.org"